kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kpng-proxy
networking:
  kubeProxyMode: "none"
  apiServerAddress: "0.0.0.0"
  podSubnet: "10.1.0.0/16"
  serviceSubnet: "10.2.0.0/16"
nodes:
- role: control-plane
- role: worker
- role: worker
